name: ChatCensor
main: ChatCensor\ChatCensor
version: 2.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
author: EvolSoft
description: A powerful chat censoring plugin
website: https://www.evolsoft.tk

commands:
 chatcensor:
   aliases: [cc, chatc, censor]
   description: ChatCensor commands.
   permission: chatcensor
 mute:
   description: Mute a player.
   permission: chatcensor.commands.mute
 unmute:
   description: Unmute a player.
   permission: chatcensor.commands.unmute
 listmuted:
   description: Get the list of muted players.
   permission: chatcensor.commands.listmuted
 addword:
   description: Add a censored word.
   permission: chatcensor.commands.addword
 removeword:
   description: Remove a censored word.
   permission: chatcensor.commands.removeword
permissions:
 chatcensor:
  default: op
  description: ChatCensor permission tree.
  children:
   chatcensor.bypass:
    default: op
    description: Bypass ChatCensor features.
    children:
     chatcensor.bypass.censor:
      default: op
      description: Bypass ChatCensor censor feature.
     chatcensor.bypass.anti-caps:
      default: op
      description: Bypass ChatCensor anti-caps feature.
     chatcensor.bypass.char-check:
      default: op
      description: Bypass ChatCensor char-check feature.
     chatcensor.bypass.anti-spam:
      default: op
      description: Bypass ChatCensor spam-check feature.
 chatcensor.commands:
  default: op
  description: ChatCensor commands permission tree.
  children:
   chatcensor.commands.help:
    default: op
    description: Let player read ChatCensor commands help.
   chatcensor.commands.info:
    default: op
    description: Let player read info about ChatCensor.
   chatcensor.commands.reload:
    default: op
    description: Let player reload ChatCensor configuration.
   chatcensor.commands.addword:
    default: op
    description: Let player add a censored word.
   chatcensor.commands.removeword:
    default: op
    description: Let player remove a censored word.
   chatcensor.commands.mute:
    default: op
    description: Let player mute a player.
   chatcensor.commands.unmute:
    default: op
    description: Let player unmute a player.
   chatcensor.commands.listmuted:
    default: op
    description: Let player show the list of muted players.
