---
censor:
 enabled: true
 allow-bypassing: false
 log-to-player: true
mute:
 log-to-player: true
 log-unmute: true
 keep-on-relogin: true
char-check:
 enabled: true
 allow-bypassing: false
 log-to-player: true
 allow-backslash: false
 allowed-chars:
  - "Q"
  - "W"
  - "E"
  - "R"
  - "T"
  - "Y"
  - "U"
  - "I"
  - "O"
  - "P"
  - "A"
  - "S"
  - "D"
  - "F"
  - "G"
  - "H"
  - "J"
  - "K"
  - "L"
  - "Z"
  - "X"
  - "C"
  - "V"
  - "B"
  - "N"
  - "M"
  - "q"
  - "w"
  - "e"
  - "r"
  - "t"
  - "y"
  - "u"
  - "i"
  - "o"
  - "p"
  - "a"
  - "s"
  - "d"
  - "f"
  - "g"
  - "h"
  - "j"
  - "k"
  - "l"
  - "z"
  - "x"
  - "c"
  - "v"
  - "b"
  - "n"
  - "m"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "0"
  - "."
  - ":"
  - ","
  - ";"
  - "-"
  - "_"
  - "|"
  - "!"
  - "/"
  - "?"
...
